### ISSUE TITLE
adapt to new yaml structure

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#401]
## Description
https://github.com/JCSDA/oops/pull/667 refactors yamls and makes them consistent within and across applications. soca would need to adapt to this before oops PR is merged.

## Solution
To adapt, see e.g. https://github.com/JCSDA/mpas-jedi/pull/340
- Variables ctor in oops is changed to take an extra string parameter ("which" variables to take); all calls to Variables ctor need be changed
- State(Geometry, Variables, Config) ctor -> State(Geometry, Config) ctor
- add State::variables() method
- change all yamls :)

## Related to
- needed by https://github.com/JCSDA/oops/pull/667
- use feature/newyaml branches from oops, saber, ioda, ufo

**Comment by shlyaeva** [comment]
For variational application, condensed changes:
```yaml
cost function:
  cost type: 4D-Var
  window begin: ...
  window length: ...
  geometry: {}            # moved here from the top level (formerly resolution)
  model:                  # moved here from the top level
    name: ... 
  analysis variables: [...]   # this used to be called "cost_function.variables"; variables to be updated
  background: {}            # Jb section is gone; this is directly under "cost function" now
  background error:         # this is former Jb.Covariance
    covariance model: hybrid  # this is former Jb.Covariance.covariance
    ensemble:
      covariance model: ensemble
      localization:
        localization method: ...
      members: []
    static:
      covariance model: ...
    ensemble weight: 0.4
    static weight: 0.6
  observations:   # this is former Jo.ObsTypes section (Jo is removed as well as Jb)
  - obs operator: {}
    obs space: {}
    obs error:    # this is former Covariance section
      covariance model: diagonal    
    obs bias: {}
    obs bias error: {}
variational:
  minimizer:      # minimizer section is moved from top level here
    algorithm: ...
  iterations:     
  - ninner: ...
    gradient norm reduction: ...
    geometry: {}   # former resolution section
    linear model:
      name: ...    # former linearmodel.version
      variable change: Identity
```

For HofX/MakeObs applications:
```yaml
geometry: {}
initial condition: {}
model:
  name: ...
forecast length: P1D    # this is a new section, it allows to run forecasts
                        # from initial condition time for forecast length
                        # regardless of observation window (in develop we run
                        # forecast for "window length"
                        # to reproduce previous behavior, set it the same as "window length"
window begin: ...       # moved level up, "Assimilation Window" removed
window length: P1D
observations:           # replaces Observations.ObsTypes
- obs space: 
    name: ...
    obsdatain: 
      obsfile: ... 
    simulated variables: [brightness_temperature]  # from simulate.variables
    channels: 1-15                                 # from simulate.channels
  obs operator: {}
```
