### ISSUE TITLE
Bug in nl change var when setting `do inverse` to `true`

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#483]
@guillaumevernieres sorry for the slow review. Hera just came back online. I ran sequentially 1) convertstate_changevar (with `do inverse: false`) -> 2) 3dvar_soca -> 3) convertstate_changevar (with `do inverse: true`) in order to do 3dvar with log transformation. First two steps worked as expected but step three crashed with the following error:
```
6: Exception: Assertion failed: varin_ in changeVarInverse, line 281 of /scratch2/NCEPDEV/marineda/Xiao.Liu/git-versions/godas-git-branches/godas/src/soca-bundle/developments/soca/bundle/oops/src/oops/base/VariableChangeBase.h
6: Assertion failed: varin_ in changeVarInverse, line 281 of /scratch2/NCEPDEV/marineda/Xiao.Liu/git-versions/godas-git-branches/godas/src/soca-bundle/developments/soca/bundle/oops/src/oops/base/VariableChangeBase.h
```
It seems convertstate_changevar cannot correctly read in variables when `do inverse` is set to `true`, regardless what input file I gave. Did I do something wrong? Thanks!

To repeat the error, simply set `do inverse: true` in the `convertstate_changevar` ctest and run.

_Originally posted by @liuxiao37k in https://github.com/JCSDA-internal/soca/pull/482#issuecomment-722146800_

**Comment by guillaumevernieres** [comment]
@liuxiao37k It's not a bug, when using the inverse you need to specify the input variables:
```yaml
variable changes:
  - variable change: Ana2Model
    do inverse: true
    rotate:
      u: [uocn]
      v: [vocn]
    log:
      var: [socn, chl]
    input variables: *soca_vars
```
But thanks for testing this, I should have added the inverse test in #482 .
