### ISSUE TITLE
2nd outer loop with ADT return "nans" when qc filters are used

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#655]
## Description
There are several issues with running outer loops currently, ADT with QC is one of them. The first failure appears in the 2nd outer loop after 33 inner iteration. 

### To Reproduce:
For unrelated reasons that will be documented in a separate issue, edit this section of [3dvarfgat_pseudo.yml](https://github.com/JCSDA-internal/soca/blob/451e71f852c430af6acca51e76883838e6baf505/test/testinput/3dvarfgat_pseudo.yml#L84) and replace 
```yaml
    - variable change: BalanceSOCA
      dsdtmax: 0.1
```
with
```yaml
    - variable change: BalanceSOCA
      dsdtmax: 0.0
```
Add an outer loop so the variational section and increase the number of outer iterations,
```yaml
variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - geometry:
      mom6_input_nml: ./inputnml/input.nml
      fields metadata: ./fields_metadata.yml
    linear model:
      name: Identity
      increment variables: *soca_vars
      variable change: Identity
      tstep: PT1H
    ninner: 150
    gradient norm reduction: 1e-15
    test: on
    diagnostics:
      departures: ombg
variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - geometry:
      mom6_input_nml: ./inputnml/input.nml
      fields metadata: ./fields_metadata.yml
    linear model:
      name: Identity
      increment variables: *soca_vars
      variable change: Identity
      tstep: PT1H
    ninner: 150
    gradient norm reduction: 1e-15
    test: on
    diagnostics:
      departures: ombg
```
run the ctest 
```console
ctest -V -R test_soca_3dvarfgat_pseudo
```
and observe the failure! :boom: 

Now comment out the filter section of the adt obsspace [here](https://github.com/JCSDA-internal/soca/blob/451e71f852c430af6acca51e76883838e6baf505/test/testinput/3dvarfgat_pseudo.yml#L127)
so it looks like this

```yaml
  - obs space:
      name: ADT
      obsdataout: {obsfile: ./Data/adt.out.nc}
      obsdatain:  {obsfile: ./Data/adt.nc}
      simulated variables: [obs_absolute_dynamic_topography]
    obs operator:
      name: ADT
    obs error:
      covariance model: diagonal
    #obs filters:
    #- *land_mask
 ```
re-run the same ctest and :tada: !!!! all good.

I suspect the issue is in the ufo, but the linear test in ufo won't pick up the problem so it will have to be debugged and tested with soca.
