### ISSUE TITLE
Bad specification of the diag of B in the second outer loop

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#666]
## Description
After more testing, it turns out that the culprit for the failure in the second outer-loop is our simple background error variable change. This issues replaces #656 and #655.

### To Reproduce
In the `test_soca_3dvarfgat` ctest yaml file, increase `ninner` to ~50 iterations and add an outer-loop:

```yaml
variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - geometry:
      mom6_input_nml: ./inputnml/input.nml
      fields metadata: ./fields_metadata.yml
    linear model:
      name: Identity
      increment variables: *soca_vars
      variable change: Identity
      tstep: PT1H
    ninner: 50
    gradient norm reduction: 1e-15
    test: on
    diagnostics:
      departures: ombg
  - geometry:
      mom6_input_nml: ./inputnml/input.nml
      fields metadata: ./fields_metadata.yml
    linear model:
      name: Identity
      increment variables: *soca_vars
      variable change: Identity
      tstep: PT1H
    ninner: 50
    gradient norm reduction: 1e-15
    test: on
    diagnostics:
      departures: ombg
```
then run the ctest with and without the **BkgErrSOCA** variable change. It converges fine without but fails with that change of variable.
