### ISSUE TITLE
Speed up the "sqrtvertloc" test

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#716]
## Description
The ``test_soca_sqrtvertloc`` test is slow. 
```console
15/68 Test #15: test_soca_enspert ............................   Passed    6.00 sec
      Start 16: test_soca_sqrtvertloc
16/68 Test #16: test_soca_sqrtvertloc ........................   Passed  130.64 sec
      Start 17: test_soca_makeobs
17/68 Test #17: test_soca_makeobs ............................   Passed    4.95 sec
```
## Solution
It's currently done on the lfs stored grid, switch to using the sub-sampled grid.

**Comment by frolovsa** [comment]
@guillaumevernieres , I am afraid i don't know how to do that.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres , I am afraid i don't know how to do that.

@frolovsa  Just using the sub-sampled geometry should speed up the test. Replace the geometry in [sqrtvertloc](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/sqrtvertloc.yml)

with that:
```yaml
geometry:
   geom_grid_file: soca_gridspec.small.nc
   mom6_input_nml: ./inputnml/input_small.nml
   fields metadata: ./fields_metadata.yml
```
You'd have to point to the low-res background too ... Not super high-priority work! I just got impatient waiting for that test to go through :)
