### ISSUE TITLE
[Bug] Scales are not set properly in SocaError

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#755]
## Description
It seems that the horizontal scales are not passed properly to bump, or, a minimum decorrelation length scale is applied in bump?

### To Reproduce:
Run the `dirac` application with the default configuration for `SocaError` from `soca-science` , remove all the variable transforms except `VertConv` and look at the scales of B x dirac in the high latitude.

The figure below is using a correlation operator from bump3D instead of the default one. This is how the background error was setup in the dirac `yaml`:
```yaml
background error:
  covariance model: SABER
  saber blocks:
  - saber block name: BUMP_NICAS
    saber central block: true
    iterative inverse: true
    input variables: [socn, tocn, ssh, hocn]
    output variables: [socn, tocn, ssh, hocn]
    bump:
      verbosity: main
      datadir: ./bump_scales
      strategy: specific_univariate
      load_nicas_local: true
      grids:
      - prefix: bump3d
        variables: [socn, tocn, hocn]
      - prefix: bump2d
        variables: [ssh]
```
From the way bump was initialize, the scales in the high latitude should be of the order of the length scale of a grid cell, this is not the case and a change from previous behaviors. 
![dirac-bump3d](https://user-images.githubusercontent.com/14031856/173125282-69f2e4e8-fb88-4f3c-8f50-89a42934aed9.png)
