### ISSUE TITLE
Replace the checkpoint application by a forecast of zero length

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#804]
@travissluka :
While putting together the `cice` model factory (probably should have been called icepack ... but whatever ...) and implementing the checkpoint application for it, I realized that we can't make a template out of the `CheckpointModel` class ... because we're using `model.initialize` and `model.finalize` in `CheckpointModel` which are declared as private in the oops base class ... ~Oops!~ Zut!

We could:
1 - delete the checkpoint app and replace it by a 0 length forecast ... where the initial conditions is the analysis. That's a bit weird, but that's basically what checkpoint does, use finalize to dump restarts.
2 - ask @ytremolet or @shlyaeva if we could publicize everything in the base Model class (`initialize`, `step`, `finalize`, `print`).
3 - or something simpler I'm sure I'm missing?

I vote for *1*

_Originally posted by @guillaumevernieres in https://github.com/JCSDA-internal/soca/issues/803#issuecomment-1232204104_

Not quite sure why we didn't do that from the get go. This:
```console
mpirun -np 2 ..../bin/soca_forecast.x theyamlbelow
```
```yaml
geometry:
  mom6_input_nml: ./inputnml/input.nml
  fields metadata: ./fields_metadata.yml

model:
  name: MOM6solo
  tstep: PT1H
  advance_mom6: 0
  model variables: [socn, tocn, hocn]
  tocn_minmax: [-1.8, 32.0]
  socn_minmax: [0.1, 38.0]

initial condition:
  read_from_file: 1
  date: &date 2018-04-15T00:00:00Z
  basename: ./Data/
  ocn_filename: ocn.3dvargodas.an.2018-04-15T00:00:00Z.nc
  state variables: [socn, tocn, hocn]

forecast length: PT0H

output:
  frequency: PT1H
  datadir: Data
  exp: mom6chkpt
  date: *date
  type: fc
```

reproduces exactly the restarts dumped by the checkpoint test ...
