### ISSUE TITLE
The Balance config needs to be updated in some of the test yaml's 

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#954]
## Description
A few (many) PR's ago, I cleaned up the configuration for the `Balance` linear variable change but I apparently forgot to update quite a few yaml's ... Oops ...
The balance configuration should look something like this:
```yaml
      - linear variable change name: BalanceSOCA
        kst:
          dsdtmax: 0.1
          dsdzmin: 3.0e-6
          dtdzmin: 1.0e-6
          nlayers: 999
        ksshts:
          nlayers: 10
        dcdt:
          filename: data_static/72x35x25/dcdt.nc
          name: dcdt
```
A few yamls in testinput are still using the old configuration.
